services:
  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./conf/mysql/scripts:/docker-entrypoint-initdb.d
      - ./conf/mysql/conf/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -uroot -proot && [ -f /var/lib/mysql/initialization-complete.flag ]"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  is-as-km:
    build:
      context: .
      dockerfile: ./dockerfiles/is-as-km/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-k", "--fail", "https://localhost:9443/api/health-check/v1.0/health"]
      interval: 10s
      start_period: 180s
      retries: 20
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./conf/is-as-km/repository/conf/deployment.toml:/home/wso2carbon/wso2is-7.1.0/repository/conf/deployment.toml
      # - ./conf/is-as-km/repository/resources/conf/templates/repository/conf/identity/identity.xml.j2:/home/wso2carbon/wso2is-7.1.0/repository/resources/conf/templates/repository/conf/identity/identity.xml.j2
      # - ./conf/is-as-km/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2is-7.1.0/repository/resources/security/client-truststore.jks
      # - ./conf/is-as-km/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2is-7.1.0/repository/resources/security/wso2carbon.jks
    ports:
      - "9444:9443"
      - "9764:9763"
  api-manager:
    build:
      context: .
      dockerfile: ./dockerfiles/apim/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9763/services/Version"]
      interval: 10s
      start_period: 180s
      retries: 20
    depends_on:
      mysql:
        condition: service_healthy
      is-as-km:
        condition: service_healthy
    volumes:
       - ./conf/apim/repository/conf/deployment.toml:/home/wso2carbon/wso2am-4.6.0/repository/conf/deployment.toml
       # - ./conf/apim/repository/resources/security/client-truststore.jks:/home/wso2carbon/wso2am-4.6.0/repository/resources/security/client-truststore.jks
       # - ./conf/apim/repository/resources/security/wso2carbon.jks:/home/wso2carbon/wso2am-4.6.0/repository/resources/security/wso2carbon.jks
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
